/**
 * Behavior-focused integration tests for the generic documentation generator.
 *
 * These tests exercise the public API (`GenericGenerator` / `generateDocs`)
 * end-to-end: a real temp-dir input file is written to disk, parsed, categorized,
 * enriched, and rendered to markdown. The returned markdown is then written to a
 * temp output dir so we can assert the on-disk documentation file matches.
 *
 * NOTE ON BEHAVIOR: `generateDocs` does NOT itself write to `config.output`. It
 * returns `{ markdown, stats, lineCount }`; persisting the markdown is the
 * caller's responsibility. These tests assert that actual behavior (the result
 * object) and persist the markdown themselves to verify file content.
 */

import { describe, it, expect, afterEach } from 'vitest';
import { mkdtemp, rm, writeFile, readFile, mkdir } from 'node:fs/promises';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { GenericGenerator, generateDocs, type GeneratorConfig } from './generic-generator';

// Track temp dirs created during a test so afterEach can clean them up.
const tempDirs: string[] = [];

async function makeTempDir(): Promise<string> {
  const dir = await mkdtemp(join(tmpdir(), 'generic-gen-'));
  tempDirs.push(dir);
  return dir;
}

afterEach(async () => {
  // Guarded cleanup: remove every temp dir we created, ignore if already gone.
  while (tempDirs.length > 0) {
    const dir = tempDirs.pop();
    if (!dir) continue;
    await rm(dir, { recursive: true, force: true }).catch(() => {
      /* best-effort cleanup */
    });
  }
});

describe('generateDocs - JSON array input (end-to-end)', () => {
  // Shared fixture builder: writes a JSON array of "operations" and returns a
  // config that categorizes them and renders a markdown table.
  async function setupJsonFixture(): Promise<{
    input: string;
    output: string;
    config: GeneratorConfig;
  }> {
    const dir = await makeTempDir();
    const input = join(dir, 'operations.json');
    const output = join(dir, 'out', 'operations.md');

    const items = [
      { name: 'getUser', type: 'query', value: 'SELECT * FROM users' },
      { name: 'createUser', type: 'mutation', value: 'INSERT INTO users' },
      { name: 'deleteUser', type: 'mutation', value: 'DELETE FROM users' },
      { name: 'healthCheck', type: 'system', value: 'ping' },
    ];
    await writeFile(input, JSON.stringify(items, null, 2), 'utf-8');

    const config: GeneratorConfig = {
      input,
      output,
      parser: { type: 'json' }, // no path -> array consumed as-is
      categories: [
        { name: 'Queries', match: (item) => (item as { type?: string }).type === 'query' },
        {
          name: 'Mutations',
          match: (item) => (item as { type?: string }).type === 'mutation',
        },
      ],
      // Dynamic enrichment: derive a "badge" field from each item's type.
      enrichments: [
        {
          field: 'badge',
          value: (item) => ((item as { type?: string }).type === 'mutation' ? 'WRITE' : 'READ'),
        },
      ],
      // Static description mapping keyed by item.name.
      descriptions: {
        getUser: 'Fetch a user by id',
      },
      template: {
        title: 'Database Operations',
        source: 'operations.json',
        showStats: true,
        showTOC: true,
        columns: [
          { header: 'Name', field: 'name' },
          { header: 'Type', field: 'type' },
          { header: 'Badge', field: 'badge' },
          { header: 'Description', field: 'description' },
        ],
        footer: 'Generated by docs-engine.',
      },
    };

    return { input, output, config };
  }

  it('computes stats: total, category count, per-category counts, uncategorized', async () => {
    const { config } = await setupJsonFixture();

    const result = await generateDocs(config);

    expect(result.stats.totalItems).toBe(4);
    expect(result.stats.categoryCount).toBe(2);
    expect(result.stats.itemsByCategory).toEqual({ Queries: 1, Mutations: 2 });
    expect(result.stats.uncategorized).toBe(1);
  });

  it('returns markdown and a lineCount matching the markdown line count', async () => {
    const { config } = await setupJsonFixture();

    const result = await generateDocs(config);

    expect(typeof result.markdown).toBe('string');
    expect(result.markdown.length).toBeGreaterThan(0);
    expect(result.lineCount).toBe(result.markdown.split('\n').length);
  });

  it('renders title, source line, stats and a table-of-contents section', async () => {
    const { config } = await setupJsonFixture();

    const result = await generateDocs(config);
    const md = result.markdown;

    expect(md).toContain('# Database Operations');
    expect(md).toContain('> **Source**: operations.json');
    // showStats section
    expect(md).toContain('### Statistics');
    expect(md).toContain('- **Total items**: 4');
    expect(md).toContain('- **Categories**: 2');
    // showTOC section with per-category counts and slugified anchors
    expect(md).toContain('## Categories');
    expect(md).toContain('- [Queries](#queries) (1 items)');
    expect(md).toContain('- [Mutations](#mutations) (2 items)');
  });

  it('groups items into category sections (uncategorized excluded from sections)', async () => {
    const { config } = await setupJsonFixture();

    const result = await generateDocs(config);
    const md = result.markdown;

    expect(md).toContain('## Queries');
    expect(md).toContain('## Mutations');
    // The internal uncategorized bucket key must never leak into output.
    expect(md).not.toContain('__uncategorized__');
    // The uncategorized item ('healthCheck', renamed category 'Other') is not
    // rendered as its own section because sections skip the uncategorized bucket.
    expect(md).not.toContain('## Other');
    expect(md).not.toContain('healthCheck');

    // Queries should appear before Mutations (insertion order of category rules).
    expect(md.indexOf('## Queries')).toBeLessThan(md.indexOf('## Mutations'));
  });

  it('renders a markdown table with the configured column headers and rows', async () => {
    const { config } = await setupJsonFixture();

    const result = await generateDocs(config);
    const md = result.markdown;

    // Header + separator row.
    expect(md).toContain('| Name | Type | Badge | Description |');
    expect(md).toContain('| --- | --- | --- | --- |');

    // Row for the single query item, including enrichment (badge) and the
    // static description mapping applied via descriptions[getUser].
    expect(md).toContain('| getUser | query | READ | Fetch a user by id |');
  });

  it('applies dynamic enrichment rules per item (badge WRITE for mutations)', async () => {
    const { config } = await setupJsonFixture();

    const result = await generateDocs(config);
    const md = result.markdown;

    // Both mutation rows get badge 'WRITE'. They have no description mapping, so
    // the description column renders 'undefined' (String(undefined)) since the
    // raw JSON items carry no description field. This asserts ACTUAL behavior.
    expect(md).toContain('| createUser | mutation | WRITE | undefined |');
    expect(md).toContain('| deleteUser | mutation | WRITE | undefined |');
  });

  it('appends the footer after a horizontal rule', async () => {
    const { config } = await setupJsonFixture();

    const result = await generateDocs(config);
    const md = result.markdown;

    expect(md).toContain('---');
    expect(md).toContain('Generated by docs-engine.');
    // Footer comes after the last category section.
    expect(md.indexOf('Generated by docs-engine.')).toBeGreaterThan(md.indexOf('## Mutations'));
  });

  it('persists the returned markdown to the output dir and the file content matches', async () => {
    const { output, config } = await setupJsonFixture();

    const result = await generateDocs(config);

    // The generator does not write files itself; the caller persists the result.
    await mkdir(join(output, '..'), { recursive: true });
    await writeFile(output, result.markdown, 'utf-8');

    const onDisk = await readFile(output, 'utf-8');
    expect(onDisk).toBe(result.markdown);
    expect(onDisk).toContain('# Database Operations');
    expect(onDisk).toContain('| getUser | query | READ | Fetch a user by id |');
  });
});

describe('generateDocs - JSON object path extraction', () => {
  it('extracts items from a nested path and renders them (package.json scripts style)', async () => {
    const dir = await makeTempDir();
    const input = join(dir, 'package.json');
    await writeFile(
      input,
      JSON.stringify({
        name: 'demo',
        scripts: {
          build: 'tsup',
          test: 'vitest',
        },
      }),
      'utf-8'
    );

    const config: GeneratorConfig = {
      input,
      output: join(dir, 'scripts.md'),
      parser: { type: 'json', path: 'scripts' },
      // parseJSON turns the object into items shaped { name, value }. A regex
      // string rule matches against String(item.name ?? item.value ?? ...).
      categories: [{ name: 'All Scripts', match: '.*' }],
      template: {
        title: 'NPM Scripts',
        columns: [
          { header: 'Script', field: 'name' },
          { header: 'Command', field: 'value' },
        ],
      },
    };

    const result = await generateDocs(config);

    expect(result.stats.totalItems).toBe(2);
    expect(result.stats.itemsByCategory).toEqual({ 'All Scripts': 2 });
    expect(result.stats.uncategorized).toBe(0);

    const md = result.markdown;
    expect(md).toContain('## All Scripts');
    expect(md).toContain('| Script | Command |');
    expect(md).toContain('| build | tsup |');
    expect(md).toContain('| test | vitest |');
  });
});

describe('generateDocs - regex string category rules and column formatters', () => {
  it('matches via regex strings and applies a column format function', async () => {
    const dir = await makeTempDir();
    const input = join(dir, 'routes.json');
    await writeFile(
      input,
      JSON.stringify([
        { name: 'GET /users', value: 'list users' },
        { name: 'POST /users', value: 'create user' },
        { name: 'GET /posts', value: 'list posts' },
      ]),
      'utf-8'
    );

    const config: GeneratorConfig = {
      input,
      output: join(dir, 'routes.md'),
      parser: { type: 'json' },
      // Regex string rules tested against item.name.
      categories: [
        { name: 'Reads', match: '^GET ' },
        { name: 'Writes', match: '^POST ' },
      ],
      template: {
        title: 'Routes',
        columns: [
          {
            header: 'Endpoint',
            field: 'name',
            // Formatter wraps the value in backticks.
            format: (v) => '`' + String(v) + '`',
          },
        ],
      },
    };

    const result = await generateDocs(config);

    expect(result.stats.itemsByCategory).toEqual({ Reads: 2, Writes: 1 });
    const md = result.markdown;
    expect(md).toContain('## Reads');
    expect(md).toContain('## Writes');
    // Formatter applied -> backtick-wrapped endpoint.
    expect(md).toContain('| `GET /users` |');
    expect(md).toContain('| `POST /users` |');
  });
});

describe('generateDocs - custom parser path', () => {
  it('uses a custom parse function and receives the full config as second arg', async () => {
    const dir = await makeTempDir();
    const input = join(dir, 'data.txt');
    await writeFile(input, 'alpha\nbeta\ngamma', 'utf-8');

    const config: GeneratorConfig = {
      input,
      output: join(dir, 'data.md'),
      parser: {
        type: 'custom',
        // Turn each non-empty line into an item.
        parse: (content) =>
          content
            .split('\n')
            .filter(Boolean)
            .map((line) => ({ name: line })),
      },
      categories: [{ name: 'Words', match: '.*' }],
      template: {
        title: 'Words',
        columns: [{ header: 'Word', field: 'name' }],
      },
    };

    const result = await generateDocs(config);

    expect(result.stats.totalItems).toBe(3);
    expect(result.stats.itemsByCategory).toEqual({ Words: 3 });
    expect(result.markdown).toContain('| alpha |');
    expect(result.markdown).toContain('| gamma |');
  });
});

describe('generateDocs - edge cases', () => {
  it('handles empty input (empty JSON array): zero items, no category sections', async () => {
    const dir = await makeTempDir();
    const input = join(dir, 'empty.json');
    await writeFile(input, '[]', 'utf-8');

    const config: GeneratorConfig = {
      input,
      output: join(dir, 'empty.md'),
      parser: { type: 'json' },
      categories: [{ name: 'Anything', match: '.*' }],
      template: {
        title: 'Empty Report',
        showStats: true,
        columns: [{ header: 'Name', field: 'name' }],
      },
    };

    const result = await generateDocs(config);

    expect(result.stats.totalItems).toBe(0);
    expect(result.stats.categoryCount).toBe(0);
    expect(result.stats.itemsByCategory).toEqual({});
    expect(result.stats.uncategorized).toBe(0);

    const md = result.markdown;
    expect(md).toContain('# Empty Report');
    expect(md).toContain('- **Total items**: 0');
    // No items -> no category section rendered (empty buckets are deleted).
    expect(md).not.toContain('## Anything');
  });

  it('routes non-matching items into the uncategorized bucket (counted, not sectioned)', async () => {
    const dir = await makeTempDir();
    const input = join(dir, 'nomatch.json');
    await writeFile(input, JSON.stringify([{ name: 'foo' }, { name: 'bar' }]), 'utf-8');

    const config: GeneratorConfig = {
      input,
      output: join(dir, 'nomatch.md'),
      parser: { type: 'json' },
      // A rule that never matches any item name.
      categories: [{ name: 'Impossible', match: '^ZZZ_NO_MATCH$' }],
      template: {
        title: 'No Matches',
        columns: [{ header: 'Name', field: 'name' }],
      },
    };

    const result = await generateDocs(config);

    expect(result.stats.totalItems).toBe(2);
    expect(result.stats.categoryCount).toBe(0);
    expect(result.stats.uncategorized).toBe(2);
    // Neither the matched category (empty, deleted) nor an 'Other' section render.
    expect(result.markdown).not.toContain('## Impossible');
    expect(result.markdown).not.toContain('## Other');
  });

  it('throws when the JSON path does not exist (parser error propagates)', async () => {
    const dir = await makeTempDir();
    const input = join(dir, 'bad-path.json');
    await writeFile(input, JSON.stringify({ a: 1 }), 'utf-8');

    const config: GeneratorConfig = {
      input,
      output: join(dir, 'bad-path.md'),
      parser: { type: 'json', path: 'doesNotExist' },
      categories: [],
      template: { title: 'X', columns: [] },
    };

    await expect(generateDocs(config)).rejects.toThrow('Path "doesNotExist" not found in JSON');
  });

  it('rejects when the input file does not exist', async () => {
    const dir = await makeTempDir();
    const config: GeneratorConfig = {
      input: join(dir, 'missing.json'),
      output: join(dir, 'missing.md'),
      parser: { type: 'json' },
      categories: [],
      template: { title: 'X', columns: [] },
    };

    await expect(generateDocs(config)).rejects.toThrow();
  });
});

describe('GenericGenerator class', () => {
  it('generate() produces the same result as the generateDocs() helper', async () => {
    const dir = await makeTempDir();
    const input = join(dir, 'items.json');
    await writeFile(input, JSON.stringify([{ name: 'one' }, { name: 'two' }]), 'utf-8');

    const config: GeneratorConfig = {
      input,
      output: join(dir, 'items.md'),
      parser: { type: 'json' },
      categories: [{ name: 'Items', match: '.*' }],
      template: {
        title: 'Items',
        columns: [{ header: 'Name', field: 'name' }],
      },
    };

    const viaClass = await new GenericGenerator(config).generate();
    const viaHelper = await generateDocs(config);

    expect(viaClass.stats).toEqual(viaHelper.stats);
    expect(viaClass.markdown).toBe(viaHelper.markdown);
    expect(viaClass.lineCount).toBe(viaHelper.lineCount);
  });
});
